# 一.自定义变量
# 初始化网站有关变量
title: Mi Mao
description: 用起来更舒适
url: https://github.com/mimao-littlemouse/Mi Mao
avatar: /avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg

# 自定义 Jekyl SEO Tag（优化搜索结果）
social:
  name: Mi Mao
  links:
    - https://github.com/mimao-littlemouse/
lang: en

# 自定义集合
collections:
  staff_members:
    output: true

# 二.网站所需的配置变量
# Gems插件依赖
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# 自定义Jekyll中不需要的文件或文件夹
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - mimao.gemspec
  - Dockerfile

# 启用sass 并指定sass文件夹的路径和名称
sass:
  sass_dir: _sass
  style: :compressed


# 三.其他选项（自定义）

