# 配置 SEO 标签选项（参见：官网 https://github.com/jekyll/jekyll-seo-tag ；文档地址 https://github.com/jekyll/jekyll-seo-tag/blob/master/docs）；
# 网页站点标题
title: Mi Mao
# 网页 简要描述（网站的描述 都是在 页面没有定义 title的时候，即：page.title没有定义的时候显示）
# 定义了 简要描述 title中优先显示简要描述 而不是 详细描述，但详细描述有利于 seo的搜索优化
# 优先级：page.title tagline description
tagline: nhao
# 网页 详细描述
description: 用起来更舒适
# 网站地址（默认：会是 site.github.url）
# 因为该项目会部署在 github上，所以url是github项目介绍地址
# 网站的完整URL。注意：默认情况下将使用site.github.url
url: https://github.io/mimao-littlemouse/jekyll-blog
# 全局配置 个人作者信息
author: 
  name: liuzhiqiang
# 配置 推特信息（默认以卡片的摘要方式呈现）(我没有，所以注释掉)
# twitter:
#   username: your username
#   card: summary
# 配置 脸书信息（由于没有用过 脸书，所以注释）
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
# 搜索页面 查找该网站时，在组织一栏中 会显示的图标（该图标可以是 公司的图标 也可以是个人图标）
logo: /assets/logo.png
# 指定社交信息
social:
  # 如果用户或组织名称与站点名称不一致时，进行配置
  # 不同于 title站点名称时，才进行配置（默认：与title名称一致）
  name: MiMao LittleMouse
  # 一系列指向个人的社交媒体资料的链接
  links:
    - https://github.com/mimao-littlemouse/
# 搜索控制台 或者 叫做站长工具的验证码通行码（由于 并未使用过，所以注释）
# 据介绍，该工具，可以提升网站在 浏览器中搜索的排名
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234

lang: en

# Gems插件依赖
plugins:
  - jekyll-seo-tag # jekyll-seo-tag 
  - jekyll-feed # jekyll-feed 用于生成jekyll帖子(必要选项 title(或name)站点名称 description站点详细介绍 url站点地址 auther全局的作者信息  )
  - jekyll-sitemap  # jekyll-sitemap 站点地图 用于生成 sitemap.xml文件(必要选项 url站点地址（由于seo中已经定义，所以无需再次定义）)

# 自定义Jekyll中不需要的文件或文件夹
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - mimao.gemspec
  - Dockerfile

# 启用sass 并指定sass文件夹的路径和名称
sass:
  sass_dir: _sass
  style: compressed


# 三.其他选项（自定义）

# 自定义集合
collections_dir: articles
collections:
  python:
    output: false