#!/bin/sh

# 构建时，只会生成目标文件，不会启动服务
# 
# 根据 不同环境配置 相关命令行即可
#
# 可指定的选项有：
# 基本url地址头
# --baseurl /blog
# 启用安全模式（用于 模拟部署至github后的效果）
# --safe 可在_config中配置
# 用于生成 liquid配置文件，以鉴定站点性能瓶颈
# --profile 可在config中进行配置
# 提升站点性能，进行增量构建（只对更改的页面和帖子进行构建）
# --incremental 可在config中进行配置
# 指定日志级别（ info(默认), warn, or error）
# JEKYLL_LOG_LEVEL=info
# 打印详细输出
# --verbose 可在config中进行配置
# 不输出，开启静音模式
# --quiet 可在config中进行配置
# 出现错误时显示完整的回溯
# --trace
# 在生成中使用特定的环境值(默认：development)
# JEKYLL_ENV=development或production
# 在修改文件时启用站点的自动重新生成（注意：在发布至github上时，如需查看其容器日志，该选项最好不启用）
# --watch 在serve中默认开启（如需取消，可以带上: --no-watch）

# 推荐在命令行中进行配置（便于管理配置）

# 共用
# 目前无

# 开发
jekyll_env="development"
# 生产
# jekyll_env="production"

# 开发
JEKYLL_ENV=${jekyll_env} bundle exec jekyll build --trace --watch
# 生产
# JEKYLL_ENV=${jekyll_env} bundle exec jekyll build --baseurl "/jekyll-blog"