#!/bin/sh

cat << EOF

- jekyll-seo-tag # jekyll-seo-tag 
  可参见：https://github.com/jekyll/jekyll-seo-tag 
- jekyll-feed # jekyll-feed 用于生成jekyll帖子(必要选项 title(或name)站点名称 description站点详细介绍 url站点地址 auther全局的作者信息  )
  可参见：https://github.com/jekyll/jekyll-feed
- jekyll-sitemap  # jekyll-sitemap 站点地图 用于生成 sitemap.xml文件(必要选项 url站点地址（由于seo中已经定义，所以无需再次定义）)
  可参见：https://github.com/jekyll/jekyll-sitemap
- jekyll-watch # 其用于修改文件，自动刷新）只需在 构建jekyll时，加上 --watch参数即可 运行jekyll时，默认加上了 --watch参数
  可参见：https://github.com/jekyll/jekyll-watch
- jekyll-avatar # 根据用户名自动生成 github上的头像（例如：{% avatar mimao-littlemouse %} 会生成：img标签 classlist有avatar avatar-small 高宽40px）
- jekyll-redirect-from # 用于设置重定向的插件
- jemoji # github风格的emoji
  可参见：https://github.com/jekyll/jemoji
- rouge # markdown高亮显示的插件
  可参见：https://github.com/rouge-ruby/rouge
- kramdown-parser-gfm
  可参见：https://github.com/kramdown/parser-gfm
- webrick # HTTP服务器工具包
  WEBrick是一个HTTP服务器工具包，可以配置为HTTPS服务器、代理服务器和虚拟主机服务器。
  WEBrick具有服务器操作和HTTP访问的完整日志记录功能。
  除了RFC 2617中没有的算法之外，WEBrick还支持基本身份验证和摘要身份验证。
  一个WEBrick服务器可以由多个WEBrink服务器或servlet组成，以在每个主机或每个路径的基础上提供不同的行为。
  WEBrick包括用于处理CGI脚本、ERB页面、Ruby块和目录列表的servlet。
  WEBrick还包括用于守护进程、以更高的权限级别启动进程和删除权限的工具。
  在jekyll中用于启动web服务
  可参见：https://github.com/ruby/webrick
# github中 默认启用 不能禁用的插件
- jekyll-coffeescript
- jekyll-default-layout
- jekyll-gist
- jekyll-github-metadata
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-titles-from-headings
- jekyll-relative-links # 用于在markdown中配置相对链接，让 []() 中的相对链接起作用
# github中 默认启用 不能禁用的插件 已经列出

EOF

# gem "jekyll-seo-tag"

# gem "jekyll-feed"

# gem "jekyll-sitemap"

# gem "jekyll-watch"

# gem "jekyll-avatar"

# gem "jekyll-redirect-from"

# gem "jemoji"

# gem "rouge"

# gem "kramdown-parser-gfm"

# gem "webrick"


# # 以下是github中 默认启用 不能禁用的插件

# gem "jekyll-coffeescript"

# gem "jekyll-default-layout"

# gem "jekyll-gist"

# gem "jekyll-github-metadata"

# gem "jekyll-optional-front-matter"

# gem "jekyll-paginate"

# gem "jekyll-readme-index"
# # 渲染标题（没有指定 任何title的时候，从文档中寻找标题给页面）
# gem "jekyll-titles-from-headings"
# # 配置相对链接的
# gem "jekyll-relative-links"