#!/bin/sh

# 开发环境 serve_dev

# 开发环境下的运行jekyll（由于 jekyll服务是先构建，再运行服务，所以得区分不同环境下的运行）
# 设定主机名 端口 自动刷新浏览器 自动打开浏览器 显示目录列表 指定读取开发环境下的配置文件
# 还可指定的选项有：
# 用于生成 liquid配置文件，以鉴定站点性能瓶颈
# --profile 可在config中进行配置
# 提升站点性能，进行增量构建（只对更改的页面和帖子进行构建）
# --incremental 可在config中进行配置
# 指定日志级别（ info(默认), warn, or error）
# JEKYLL_LOG_LEVEL=info
# 打印详细输出
# --verbose 可在config中进行配置
# 不输出，开启静音模式
# --quiet 可在config中进行配置
# 出现错误时显示完整的回溯
# --trace
# 在生成中使用特定的环境值(默认：development)
# JEKYLL_ENV=production
# 在修改文件时启用站点的自动重新生成
# --watch 在serve中默认开启（如需取消，可以带上: --no-watch）

jekyll_env="development"
github_token="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"

# 此外，在开发环境中，特意设置与生产环境下的端口不同，开发环境，使用4200端口 生产环境使用：4000端口
JEKYLL_ENV=${jekyll_env} JEKYLL_GITHUB_TOKEN=${github_token} bundle exec jekyll serve --host 0.0.0.0 --port 4200 --livereload --open-url --show-dir-listing --config _config-dev.yml