name: Jekyll-Blog Docker-Image

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build jekyll-blog
      run: docker build -t jekyll-blog .

    - name: Run container blog
      run: |
        cd ..
        docker run -itd -v /jekyll-blog:/blog --name="blog" jekyll-blog /bin/bash
    
    -name: Restart container blog
      run: |
        docker restart blog
        cd jekyll-blog
    
    - name: Check GitHub Pages status
      uses: crazy-max/ghaction-github-status@v3
      with:
        pages_threshold: major_outage

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Mkdir site and cp -r _site/* site and cd directory
      run: |
        mkdir site
        cp -rf _site/* site
        cd site

    - name: Deploy to Github Pages
      # 如果 出现git 128错误，务必确保 action常规设置中的 action的读和写的权限已打开
      if: success()
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        build_dir: site
        jekyll: false
        verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        
        
    
    
